// Items
export const FETCH_ITEMS_END = 'FETCH_ITEMS_END';
export const FETCH_ITEMS_ERROR = 'FETCH_ITEMS_ERROR';
export const FETCH_ITEMS_START = 'FETCH_ITEMS_START';
export const FETCH_ITEMS_REQUESTED = 'FETCH_ITEMS_REQUESTED';

// Item
export const FETCH_ITEM_END = 'FETCH_ITEM_END';
export const FETCH_ITEM_ERROR = 'FETCH_ITEM_ERROR';
export const FETCH_ITEM_START = 'FETCH_ITEM_START';
export const FETCH_ITEM_REQUESTED = 'FETCH_ITEM_REQUESTED';
